apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: multitier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: "381492261524.dkr.ecr.eu-west-1.amazonaws.com/nodeapp:latest"
        name: app
        ports:
        - containerPort: 3000
          name: app
      imagePullSecrets:
      - name: ecr-secret
