apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: appredis
spec:
  type: NodePort
  ports:
  - name: "app-service"
    port: 3000
    targetPort: 80
    nodePort: 31002
  selector:
    app: app
  