apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: multitier
spec:
  type: NodePort
  ports:
  - name: "app-service"
    port: 5000
    targetPort: 80
    nodePort: 31003
  selector:
    app: app
  