apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pythonapp
  name: pythonapp
  namespace: multitier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - image: "381492261524.dkr.ecr.eu-west-1.amazonaws.com/pythonapp:latest"
        name: pythonapp
      imagePullSecrets:
      - name: ecr-secret  
        ports:
        - containerPort: 80
          name: pythonapp