---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::381492261524:user/devlopers
      username: devlopers

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: multitier
  name: pod-service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list","get","watch"]
- apiGroups: ["extensions","apps"]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-service-reader-binding
  namespace: multitier
subjects:
- kind: User
  name: devlopers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-service-reader
  apiGroup: rbac.authorization.k8s.io

----

