apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: twotier  # Specify the namespace here
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXNkYg==
