apiVersion: v1
kind: Service
metadata:
  labels:
    app: springapp
  name: springapp
  namespace: multitier
spec:
  type: NodePort
  ports:
  - name: "springapp-service"
    port: 6868
    targetPort: 80
    nodePort: 31004
  selector:
    app: springapp
  